## 学习资料

- [斯坦福CS231n—深度学习与计算机视觉(资料汇总)](https://www.52ml.net/20815.html)
- [TensorFlow深度学习，一篇文章就够了](http://blog.jobbole.com/105602/)
- [【干货合集】深度学习入门与实战](https://zhuanlan.zhihu.com/p/27196647)
- [新手向的TensorFlow学习之路2（Learning paths 2）](http://hp.stuhome.net/index.php/2017/03/28/tensorflow-learning-paths-2/)
- [AI算法精研学习资料-附视频及讲师PPT](https://www.jianshu.com/p/39f95d5c18c7)
1. Stanford 的 CS 20SI 课程，专门针对 TensorFlow 的课程，[Tensorflow for Deep Learning Research](https://web.stanford.edu/class/cs20si/)
2. 两本书籍：[Tensorflow Machine Learning Cookbook](https://github.com/nfmcclure/tensorflow_cookbook) + [TensorFlow for Machine Intelligence](https://www.safaribooksonline.com/library/view/tensorflow-for-machine/9781939902351/)
3. Udacity公开课:[深度学习](http://cn.udacity.com/course/deep-learning--ud730)
### Welcome to Jupyter!
- [Jupyter Try](https://jupyter.org/try)
- [Jupyter Hub 教程](https://binderhub.readthedocs.io/en/latest/)
This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:


```sh
# first, always upgrade pip!
pip install --upgrade pip
pip install --upgrade ipython jupyter
```
Start the notebook in the tutorial directory:
```sh
cd ipython-in-depth
jupyter notebook
```
### Python 优秀教程
- [Learn Python](https://learnpython.org/)
- [Learn Python the Hard Way](https://learnpythonthehardway.org/book/)
- [Practical Machine Learning Tutorial with Python Introduction](https://pythonprogramming.net/machine-learning-tutorial-python-introduction/) 涵盖了与机器学习相关的概念、算法、理论、应用程序等.
- [Introduction to Neural Networks](https://pythonprogramming.net/neural-networks-machine-learning-tutorial/)

### 深度学习（Deep Learning，DL）
虽然 Tensorflow 已经封装好了大部分 DL 的细节，但是如果不了解 DL 的相关核心概念，就会很难着手分析问题。首先强烈推荐教程[Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/)，通读一遍，然后还有深度学习圣经[Deep Learning](http://www.deeplearningbook.org/)，可以快速浏览或者只看自己不太明白的地方，还有[Welcome to the Deep Learning Tutorial! ](http://deeplearning.stanford.edu/tutorial/)分块介绍的，还有几篇blog，[Conv Nets: A Modular Perspective](https://colah.github.io/posts/2014-07-Conv-Nets-Modular/)讲的是卷积神经网络。图像识别用的比较多的就是卷积神经网络，这篇可以看看。
 [Deep Learning Tutorials](http://deeplearning.net/tutorial/)也是不错的。
 
### TensorFlow 教程
- [官方教程](https://www.tensorflow.org/tutorials/)
- [官方文档中文版](http://www.tensorfly.cn/)
- [TensorFlow 文档中文翻译版](http://wiki.jikexueyuan.com/project/tensorflow-zh/)
- [tensorflow cookbook](https://github.com/nfmcclure/tensorflow_cookbook)
- [斯坦福教程](https://web.stanford.edu/class/cs20si/syllabus.html)
- [Tensorflow的教程](http://learningtensorflow.com/)
- [莫烦 TensorFlow](https://morvanzhou.github.io/tutorials/machine-learning/tensorflow/)
- [Introduction to Deep Learning with TensorFlow](https://pythonprogramming.net/tensorflow-introduction-machine-learning-tutorial/)
- [Deep Learning with TensorFlow - Creating the Neural Network Model](https://pythonprogramming.net/tensorflow-deep-neural-network-machine-learning-tutorial/)

- [在Android端使用 TensorFlow](http://hp.stuhome.net/index.php/2017/02/17/tensorflow-on-android/) 


### 优质 blog
- [Hackery, Math](http://acko.net/)
- [colah's blog](https://colah.github.io/)
- [ Café, bonne nuit](https://ireneli.eu/)
- [Mike Bostock](https://bost.ocks.org/mike/)

### 优秀课程资源
[使用TensorFlow |创建深度学习应用程序](https://www.kadenze.com/courses/creative-applications-of-deep-learning-with-tensorflow/info)以应用为导向的课程，通过鼓励探索创造性思维和深层神经网络的创造性应用，教你Tensorflow的基础知识以及最先进的算法，强烈鼓励尝试这门课程。这是唯一全面的在线课程，将教会你如何使用 Tensorflow 和开发您的创造潜力，了解如何应用这些技术创建神经网络。

建议你看一下[Deep Learning with TensorFlow](https://cognitiveclass.ai/courses/deep-learning-tensorflow/)课程。同样查看目录中的其他数据科学和机器学习课程。课程是完全免费的，并且许多都有完成证书和IBM支持的开放徽章。

### [如何开始学习使用TensorFlow？](https://yq.aliyun.com/articles/71257?utm_campaign=wenzhang&utm_medium=article&utm_source=QQ-qun&utm_content=m_12436)

## 优秀的 GitHub
- [ahangchen/GDLnotes](https://github.com/ahangchen/GDLnotes)
- [ahangchen/GoogleML](https://github.com/ahangchen/GoogleML)
- [wagamamaz](https://github.com/wagamamaz)

# TensorFlow 学习（3月 - 4 月）[caicloud/tensorflow-tutorial](https://github.com/caicloud/tensorflow-tutorial)

[TensorFlow 白皮书](https://www.jianshu.com/p/65dc64e4c81f)

In [8]:
!pip show tensorflow-gpu

Name: tensorflow-gpu
Version: 1.6.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\anaconda3\lib\site-packages
Requires: gast, protobuf, six, absl-py, tensorboard, termcolor, wheel, astor, numpy, grpcio


## 常用函数

函数|功能
:-|:-
`tf.get_default_graph()`|获取当前默认计算图
`tf.Graph()`|生成新的计算图
`tf.Graph().device()`|指定运行计算的设备

更多参考：[TensorFlow 常用的函数](http://www.cnblogs.com/q735613050/p/7777802.html)

下面举几个例子：

In [ ]:
import tensorflow as tf

为了建模方便，TensorFlow 将 `tf.constant()` 转换为一种永远输出固定值的运算。

In [10]:
a = tf.constant([1., 2.], name='a')
b = tf.constant([2., 3.], name='b')
result = a + b

`a.graph` 查看张量所属的计算图：

In [11]:
a.graph is tf.get_default_graph()

True

In [12]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.Variable(tf.zeros([2,]), name='v')
    print(v)

<tf.Variable 'v:0' shape=(2,) dtype=float32_ref>


In [13]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    print(sess.run(v))

[0. 0.]


In [14]:
g2 = tf.Graph()
with g2.as_default():
    v1 = tf.get_variable('v', [1], initializer= tf.zeros_initializer())
    print(v1)

<tf.Variable 'v:0' shape=(1,) dtype=float32_ref>


In [15]:
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope('', reuse= True):
        print(sess.run(tf.get_variable('v')))

[0.]


In [16]:
g = tf.Graph()
a = tf.constant([1., 2.], name='a')
b = tf.constant([2., 3.], name='b')
with g.device('/gpu:0'):
    result = a + b
    
with tf.Session() as sess:
    print(sess.run(result))

[3. 5.]


关于张量、计算图、会话（`tf.Session()`）的详细信息见：[TensorFlow 基础](http://www.cnblogs.com/q735613050/p/7632792.html)

## [mybinder](https://mybinder.org/)将 GitHub 上的 Jupyter NoteBook 推送至云端

[公开笔记](https://mybinder.org/v2/gh/q735613050/XinetStudio/Opening)

[个人笔记](https://mybinder.org/v2/gh/q735613050/XinetStudio/master)

$\dot x$

## 添加自己的库

In [ ]:
import sys
sys.path.append(r'E:\xinlib')

import numpy as np
import tensorflow as tf
from numpy.random import RandomState

import xin

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
batch_size = 8
rdm = RandomState(1)
X = rdm.rand(128, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

for data, label in xin.data_iter(X, Y, batch_size):
    break

In [6]:
data.shape

(8, 2)

In [7]:
label.shape

(8, 1)

In [8]:
data.dtype

dtype('float32')

## 重置计算图
```py
from tensorflow.python.framework import ops
ops.reset_default_graph()
```

### 增加维度

In [17]:
a = tf.constant([2, 3, 4, 5, 6, 6], dtype= tf.float32)
a

<tf.Tensor 'Const_2:0' shape=(6,) dtype=float32>

In [18]:
tf.shape(tf.expand_dims(a, 0))

<tf.Tensor 'Shape_2:0' shape=(2,) dtype=int32>

In [19]:
tf.expand_dims(a, 0)

<tf.Tensor 'ExpandDims_12:0' shape=(1, 6) dtype=float32>

In [20]:
tf.expand_dims(a, 1)

<tf.Tensor 'ExpandDims_13:0' shape=(6, 1) dtype=float32>

In [21]:
tf.expand_dims(a, -1)

<tf.Tensor 'ExpandDims_14:0' shape=(6, 1) dtype=float32>

In [25]:
with tf.Session() as sess:
    print(sess.run(a))

[2. 3. 4. 5. 6. 6.]


In [22]:
with tf.Session() as sess:
    print(sess.run(tf.expand_dims(a, 0)))

[[2. 3. 4. 5. 6. 6.]]


In [23]:
with tf.Session() as sess:
    print(sess.run(tf.expand_dims(a, 1)))

[[2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [6.]]


In [24]:
with tf.Session() as sess:
    print(sess.run(tf.expand_dims(a, -1)))

[[2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [6.]]


### 裁剪多余维度: `tf.squeeze`

In [26]:
import numpy as np

In [34]:
a = np.arange(1024).reshape((1, 32, 32, 1))
w = tf.squeeze(a)
w.shape

TensorShape([Dimension(32), Dimension(32)])

## 随机张量

- `tf.random_uniform(shape, minval=0, maxval=None)` 生成均匀分布的随机数  $x$：$(minval \leq x < maxval)$
更多函数参考：[TensorFlow常用的函数](http://www.cnblogs.com/q735613050/p/7777802.html)

### 张量或数组的随机化
- `tf.random_crop(input_tensor)`
- `tf.random_shuffle(input_tensor, crop_size)` 实现对张量的指定大小进行随机裁剪。

## [深度学习与计算机视觉](https://book.douban.com/subject/27125397/)
代码库地址：
https://github.com/frombeijingwithlove/dlcv_for_beginners