In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
z = tf.zeros([2, 4], tf.float32)
z

<tf.Tensor 'zeros_3:0' shape=(2, 4) dtype=float32>

In [7]:
one = tf.ones([2, 3], tf.float16)
one

<tf.Tensor 'ones_1:0' shape=(2, 3) dtype=float16>

In [9]:
filled_tsr = tf.fill([2, 3], 45)
filled_tsr

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

In [10]:
constant_tsr = tf.constant([1, 2, 3])
constant_tsr

<tf.Tensor 'Const:0' shape=(3,) dtype=int32>

In [11]:
z_like = tf.zeros_like(constant_tsr)
a_like = tf.ones_like(constant_tsr)

In [19]:
liner_tsr = tf.linspace(start= 10., stop= 1, num= 12, name= 'liner_tensor')
liner_tsr

<tf.Tensor 'liner_tensor_4:0' shape=(12,) dtype=float32>

In [20]:
with tf.Session() as sess:
    print(sess.run(liner_tsr))

[10.         9.181818   8.363636   7.5454545  6.727273   5.909091
  5.090909   4.2727275  3.4545455  2.6363635  1.818182   1.       ]


In [22]:
inter_tsr = tf.range(start= 3, limit= 18, delta= 2, dtype= tf.float32)
inter_tsr

<tf.Tensor 'range:0' shape=(8,) dtype=float32>

In [23]:
with tf.Session() as sess:
    print(sess.run(inter_tsr))

[ 3.  5.  7.  9. 11. 13. 15. 17.]


In [26]:
a = tf.convert_to_tensor(inter_tsr)
with tf.Session() as sess:
    print(sess.run(a))

[ 3.  5.  7.  9. 11. 13. 15. 17.]


In [29]:
a == inter_tsr

True

In [30]:
import numpy as np

In [31]:
b = np.array([2, 3, 4])
b1 = tf.convert_to_tensor(b)
b1

<tf.Tensor 'Const_1:0' shape=(3,) dtype=int32>

In [32]:
b == b1

False

In [45]:
val = np.arange(1, 10, 2, dtype= np.float32)
data = tf.placeholder(tf.float32)
a =tf.constant(3.)
p = tf.multiply(data, a)
sess = tf.Session()

In [49]:
for x in val:
    print(sess.run(p, feed_dict= {data: x}))

3.0
9.0
15.0
21.0
27.0


In [50]:
data.shape

TensorShape(None)

In [54]:
np.random.chisquare?

In [56]:
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.Session()

In [58]:
x_vals = np.random.normal(1, 0.1, 100)
y_vals = np.repeat(10., 100)
x_data = tf.placeholder(tf.float32, [None, 1])
y_target = tf.placeholder(tf.float32, [None, 1])
A = tf.Variable(tf.random_normal([1, 1]))
out = tf.matmul(x_data, A)
loss = tf.reduce_mean(tf.square(out - y_target))

In [60]:
opt = tf.train.GradientDescentOptimizer(0.02)
train_step = opt.minimize(loss)

In [61]:
batch_size = 32
loss_batch = []
for i in range(100):
    idx = np.random.choice(100, size= batch_size)
    x_ = np.transpose(x_vals[idx])
    y_ = np.transpose(y_vals[idx])

In [65]:
x_vals[idx]

array([1.02186005, 1.01873325, 0.95493443, 0.95716094, 0.90855158,
       1.00636671, 1.0223595 , 1.06126244, 0.91983578, 1.06654593,
       0.99828687, 1.06133468, 1.0283103 , 0.95540917, 1.06517934,
       0.83895208, 1.09282936, 1.03510749, 1.07210885, 1.29414758,
       0.96144968, 1.14071158, 0.94088895, 0.96874802, 1.09923858,
       1.15111876, 1.15719524, 1.09117143, 1.04629189, 1.01967494,
       1.08117498, 1.04629189])

In [69]:
import sys
sys.path.append('E:/xinlib')

import xin

In [72]:
xin.data_iter?

In [ ]:
# 