# 洗牌

In [1]:
SUITS = ['Clubs', 'Diamonds', 'Hearts', 'Spades']
RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King', 'Ace']

In [2]:
import random
rank = random.randrange(0, len(RANKS))
suit = random.randrange(0, len(SUITS))
print(RANKS[rank] + ' of ' + SUITS[suit])

Queen of Spades


In [3]:
# 生成一套牌
deck = []
for rank in RANKS:
    for suit in SUITS:
        card = str(rank) + ' of ' + str(suit)
        deck += [card]

In [5]:
# 洗牌
n = len(deck)
for i in range(n):
    r = random.randrange(i, n)
    temp = deck[r]
    deck[r] = deck[i]
    deck[i] = temp

In [8]:
deck[:5]

['Ace of Diamonds',
 'Jack of Hearts',
 '7 of Diamonds',
 '2 of Diamonds',
 '8 of Clubs']

下面使用 python 模块实现**洗牌**：

## `random.shuffle` 可以实现洗牌

In [10]:
random.shuffle(deck)
deck[:5]

['9 of Spades',
 '6 of Clubs',
 'Queen of Spades',
 'Ace of Spades',
 'Queen of Hearts']

## `np.random.shuffle`  也可以实现洗牌

In [11]:
import numpy as np
np.random.shuffle(deck)
deck[:5]

['3 of Clubs',
 '7 of Hearts',
 '6 of Diamonds',
 '4 of Diamonds',
 'Jack of Clubs']

# 无放回抽样（Sampling without replacement）

`random.sample(a, k)` 从数组 `a[:]` 中均匀随机分布抽取 $k$ 个样本。

In [18]:
from numpy.random import  RandomState

In [19]:
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

In [41]:
for x,y in zip(X, Y):
    print(x, y)
    break

[0.417022   0.72032449] [1.1448176486155424]


In [43]:
random.sample(list(zip(X, Y)), 8)

[(array([0.98886109, 0.74816565]), [1.706883732129045]),
 (array([0.22570934, 0.71298898]), [0.9541120536876058]),
 (array([0.01553328, 0.59348141]), [0.5620546527403518]),
 (array([0.31736241, 0.98861615]), [1.3509591628699724]),
 (array([0.12417332, 0.27918368]), [0.39494186595780334]),
 (array([0.417022  , 0.72032449]), [1.1448176486155424]),
 (array([0.87638915, 0.89460666]), [1.7592060910030372]),
 (array([0.17619626, 0.33206357]), [0.5576511324029401])]

In [32]:
random.sample(list(Y), 8)

[[1.2443681369043287],
 [0.4558037395609696],
 [0.5405042724863269],
 [0.9938036724642166],
 [0.24533699946471965],
 [0.8303161163575917],
 [1.064403391403283],
 [1.1139275495365555]]