In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

import sys
sys.path.append('E:/xinlib')
import xin
import TF
import chaos

# `tf.Tensor`

## 常量（`tf.constant`）、变量（`tf.Variable`）、op

In [30]:
x = tf.constant([5.2])
x

<tf.Tensor 'Const_7:0' shape=(1,) dtype=float32>

In [21]:
type(x) is tf.Tensor

True

In [4]:
x_ = chaos.tensor_to_ndarray(x)
x_

array([ 5.19999981], dtype=float32)

In [14]:
y = tf.Variable([0.])
print(chaos.tensor_to_ndarray(y))
y = y.assign([5])
print(chaos.tensor_to_ndarray(y))

[ 0.]
[ 5.]


In [18]:
z = tf.add
z

<function tensorflow.python.ops.gen_math_ops.add(x, y, name=None)>

In [34]:
x.shape

TensorShape([])

In [36]:
x.dtype

tf.int32

## `tf.rank` 维数

In [38]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)

<tf.Tensor 'Rank:0' shape=() dtype=int32>

### Rank 0

In [39]:
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

 \begin{remark}
**字符串**在 TensorFlow 中被视为单个item，而不是字符序列。可以有标量字符串，字符串向量等。
\end{remark}

### Rank 1

In [40]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

### Higher ranks

In [41]:
mymat = tf.Variable([[7], [11]], tf.int16)
myxor = tf.Variable([[False, True], [True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7], [11]], tf.int32)

In [2]:
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color

### 要确定 `tf.Tensor` 对象的 rank，请调用该 `tf.rank` 方法

In [43]:
rank = tf.rank(my_image)
rank

<tf.Tensor 'Rank_2:0' shape=() dtype=int32>

由上可知 `tf.rank` 对象也是一个 `tf.Tensor` 对象。

In [44]:
chaos.tensor_to_ndarray(rank)  # 在一个会话中获取 value

4

## `tf.Tensor.shape`

In [3]:
my_image.shape

TensorShape([Dimension(10), Dimension(299), Dimension(299), Dimension(3)])

In [5]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.shape(t)  # [2, 2, 3]

<tf.Tensor 'Shape:0' shape=(3,) dtype=int32>

## `tf.reshape`

In [7]:
rank_three_tensor = tf.ones([3, 4, 5])
matrix = tf.reshape(rank_three_tensor,
                    [6, 10])  # Reshape existing content into
# a 6x10 matrix
matrixB = tf.reshape(matrix, [3, -1])  #  Reshape existing content into a 3x20
# matrix. -1 tells reshape to calculate
# the size of this dimension.
matrixAlt = tf.reshape(matrixB, [4, 3, -1])  # Reshape existing content into a
#4x3x5 tensor

# Note that the number of elements of the reshaped Tensors has to match the
# original number of elements. Therefore, the following example generates an
# error because no possible value for the last dimension will match the number
# of elements.
#yet_another = tf.reshape(matrixAlt, [13, 2, -1])  # ERROR!

## `tf.Tensor.dtype `

In [8]:
# Cast a constant integer tensor into floating point.
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)

In [9]:
float_tensor.dtype

tf.float32

## `tf.Print`

In [26]:
t = tf.constant([[2, 3, 4, 5], [4 ,5 ,7, 8]])
t = [t, 2 * t, t + 5]
tf.Print(t, [t])  # This does nothing

<tf.Tensor 'Print_8:0' shape=(3, 2, 4) dtype=int32>

In [28]:
t = tf.Print(t, [t])  # Here we are using the value returned by tf.Print
t

<tf.Tensor 'Print_9:0' shape=(3, 2, 4) dtype=int32>

In [29]:
chaos.tensor_to_ndarray(t)

array([[[ 2,  3,  4,  5],
        [ 4,  5,  7,  8]],

       [[ 4,  6,  8, 10],
        [ 8, 10, 14, 16]],

       [[ 7,  8,  9, 10],
        [ 9, 10, 12, 13]]])

In [30]:
result = t + 1  # Now when result is evaluated the value of `t` will be printed.
result

<tf.Tensor 'add_7:0' shape=(3, 2, 4) dtype=int32>

In [31]:
chaos.tensor_to_ndarray(result)

array([[[ 3,  4,  5,  6],
        [ 5,  6,  8,  9]],

       [[ 5,  7,  9, 11],
        [ 9, 11, 15, 17]],

       [[ 8,  9, 10, 11],
        [10, 11, 13, 14]]])

# 创建一个简单的 TensorFlow 程序

In [31]:
import tensorflow as tf

# Create a graph.
g = tf.Graph()

# Establish the graph as the "default" graph.
with g.as_default():
    # Assemble a graph consisting of the following three operations:
    #   * Two tf.constant operations to create the operands.
    #   * One tf.add operation to add the two operands.
    x = tf.constant(8, name="x_const")
    y = tf.constant(5, name="y_const")
    sum = tf.add(x, y, name="x_y_sum")

    # Now create a session.
    # The session will run the default graph.
    with tf.Session() as sess:
        print(sum.eval())

13
