In [1]:
import sys

import tensorflow as tf
from numpy.random import RandomState
from tensorflow.python.framework import ops
ops.reset_default_graph()

sys.path.append(r'E:\xinlib')
import xin

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 1. 定义神经网络的相关参数和变量。

In [2]:
batch_size = 8
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#### 2. 设置自定义的损失函数。

In [3]:
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测。
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

In [9]:
dw = tf.gradients(loss, w1)

#### 3. 生成模拟数据集。

In [4]:
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

In [5]:
X = xin.norm(X)
X.shape

(128, 2)

In [6]:
data_iter = xin.data_iter(X, Y, batch_size)

#### 4. 训练模型。

In [6]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        for data, label in data_iter:
            sess.run([train_step, y, y_], feed_dict={x: data, y_: label})
        if i % 1000 == 0:
            print(("After %d training step(s), w1 is: " % (i)))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.8004185]
 [ 1.4735751]] 

After 1000 training step(s), w1 is: 
[[-0.8004185]
 [ 1.4735751]] 

After 2000 training step(s), w1 is: 
[[-0.8004185]
 [ 1.4735751]] 

After 3000 training step(s), w1 is: 
[[-0.8004185]
 [ 1.4735751]] 

After 4000 training step(s), w1 is: 
[[-0.8004185]
 [ 1.4735751]] 

Final w1 is: 
 [[-0.8004185]
 [ 1.4735751]]


#### 5. 重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测。

In [7]:
loss_less = 1
loss_more = 10
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        for data, label in data_iter:
            sess.run(train_step, feed_dict={x: data, y_: label})
        if i % 1000 == 0:
            print(("After %d training step(s), w1 is: " % (i)))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 1000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 2000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 3000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 4000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

Final w1 is: 
 [[-0.8113182]
 [ 1.4845988]]


#### 6. 定义损失函数为MSE。

In [8]:
loss = tf.losses.mean_squared_error(y, y_)
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        for data, label in data_iter:
            sess.run(train_step, feed_dict={x: data, y_: label})
        if i % 1000 == 0:
            print(("After %d training step(s), w1 is: " % (i)))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 1000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 2000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 3000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

After 4000 training step(s), w1 is: 
[[-0.8113182]
 [ 1.4845988]] 

Final w1 is: 
 [[-0.8113182]
 [ 1.4845988]]
